### ISSUE TITLE
Error when install 

### ISSUE THREAD

**Issue by bekeomut** [kivy-garden/garden.navigationdrawer#7]
╭─ cherry ♥  KimNhung in ~/Downloads/fourbar on master✔  ---> [12-01-2015  13:53:39]
╰─○ garden install navigationdrawer                                                                                                 
Downloading http://github.com/kivy-garden/garden.navigationdrawer/archive/master.zip ...
Traceback (most recent call last):
  File "/usr/bin/garden", line 189, in <module>
    GardenTool().main(sys.argv[1:])
  File "/usr/bin/garden", line 71, in main
    options.func()
  File "/usr/bin/garden", line 109, in cmd_install
    fd = self.download(opts.package)
  File "/usr/bin/garden", line 170, in download
    data += buf
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by gustavklopp** [comment]
Same here. Python 3.3, kivy 1.8.0

**Comment by KeyWeeUsr** [comment]
Find `.kivy` in your home folder and if there's `garden` folder, then just copy&paste the content of `master.zip` into that folder. Otherwise you'll need to create those folders. Also, this issue has nothing to do with the drawer itself, only with `garden` as the Traceback says. Issue should have been placed [here](https://github.com/kivy-garden/garden/issues).

**Comment by nishajangir** [comment]
Please help me i am new here i have download this zip file and open in pycharme. after that what i need please support me....... please
